
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path


# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import visuals
import weerrequest

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/heidi/PycharmProjects/Python/weather_app/build/assets/frame0/")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def create_date_time_str(datum, plaats):
    return (plaats + '\n' + datum['date_string'] +
            '\n' + datum['time_string'])


def start_gui(plaats, weer, color_text, background_img, datum):
    window = Tk()
    window.title('Weerbericht')
    window.geometry("859x519")
    window.configure(bg = "#530915")

    window.geometry("859x519")
    window.configure(bg = "#347BB4")


    canvas = Canvas(
        window,
        bg = "#347BB4",
        height = 519,
        width = 859,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        512.0,
        0.0,
        859.0,
        519.0,
        fill="#132648",
        outline="")





    canvas.create_text(
        548.0,
        41.0,
        anchor="nw",
        text=weer,
        fill="#FFFFFF",
        font=("RobotoSlab Medium", 15 * -1)
    )

    image_image_1 = PhotoImage(
        file=relative_to_assets(background_img))


    image_1 = canvas.create_image(
        256.0,
        260.0,
        image=image_image_1
    )

    image_1 = canvas.create_image(
        256.0,
        260.0,
        image=image_image_1
    )

    canvas.create_text(
        87.0,
        232.0,
        anchor="nw",
        text=create_date_time_str(datum, plaats),
        fill=color_text,
        font=("RobotoSlab Bold", 22 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        683.0,
        405.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#FFFFFF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(
        x=587.0,
        y=393.0,
        width=192.0,
        height=22.0
    )



    def reload_city():
        visuals.city = entry_1.get()
        window.destroy()
        weerrequest.process_data(visuals.city)

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=reload_city,
        relief="flat"
    )

    button_1.place(
        x=595.0,
        y=430.0,
        width=180.0,
        height=55.0
    )
    canvas.create_text(
        581.0,
        367.0,
        anchor="nw",
        text="Plaats:",
        fill="#FFFFFF",
        font=("RobotoSlab Regular", 13 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
